[build-system]
requires = ["setuptools", "build", "wheel", "babel", "pyfiglet", "doit", "coverage"]
build-backend = "setuptools.build_meta"

[project]
name = "task"
version = "1.0"
dependencies = ["pyfiglet",]
